### ISSUE TITLE
getHeadersByNumber 

### ISSUE THREAD

**Issue by sfsf332** [ickb/v1-interface#3]
this getHeadersByNumber Method causes too many RPC calls。 Are there any alternatives?

**Comment by phroi** [comment]
Hey @sfsf332, thank you for publicly expressing your interest in iCKB as part of the integration of iCKB in NervDAO, I personally appreciate a lot!! 🙏

> this getHeadersByNumber Method causes too many RPC calls

Not to disregard your expertise, but in my codebase exists only a single call to `getHeadersByNumber` that is [both cached and batched](https://github.com/ickb/v1-interface/blob/2656ef88989e6f33bb35ffdf5add30d0ef035881/src/queries.ts#L322-L354). This way a single header is never fetched more than a single time per session. Also only 12 iCKB deposits exist on mainnet, so not that many headers to fetch.

> Are there any alternatives?

No, not really, but I can suggest some improvements to [your codebase](https://github.com/ckb-devrel/nervdao/commit/3144c15d72bb2c651edd813a9164fd8829289e36): **start caching those `getHeadersByNumber` calls!!**

```
user@host:~/nervdao$ grep --recursive --line-number -i 'getheaderbynumber' .
./src/cores/queries.ts:444:        batch.add("getHeaderByNumber", blockNum);
./src/cores/queries.ts:496:        const header = await signer.client.getHeaderByNumber(tx.blockNumber);
./src/cores/queries.ts:525:        const header = await signer.client.getHeaderByNumber(tx.blockNumber);
./src/cores/queries.ts:556:        const header = await signer.client.getHeaderByNumber(tx.blockNumber);
./src/app/components/DashboardProfile.tsx:51:        const past = await signer.client.getHeaderByNumber(
./src/app/components/IckbStatus.tsx:24:        const past = await signer.client.getHeaderByNumber(
```

Additionally, I would like to suggest that this cache should not be implemented in the DApp, but in CCC itself. This way all DApps using CCC can get this for free. You should also evaluate which other RPC calls can be cached safely.

Love & Peace, Phroi
